ALTER TABLE Users
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE Accounts
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE Transactions
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;